# Generated by Django 5.2.7 on 2025-10-26 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foro", "0001_initial"),
        ("usuario", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificacion",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notificaciones_emitidas",
                to="usuario.perfil",
            ),
        ),
    ]
