# Generated by Django 5.2.7 on 2025-11-09 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foro", "0002_notificacion_actor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="incidencia",
            name="imagen",
        ),
        migrations.CreateModel(
            name="IncidenciaImagen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imagen", models.ImageField(upload_to="incidencias/")),
                ("orden", models.PositiveIntegerField(default=0)),
                (
                    "incidencia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imagenes",
                        to="foro.incidencia",
                    ),
                ),
            ],
            options={
                "ordering": ["orden", "id"],
            },
        ),
    ]
