# Generated by Django 5.2.7 on 2025-11-09 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foro", "0003_remove_incidencia_imagen_incidenciaimagen"),
    ]

    operations = [
        migrations.AddField(
            model_name="incidencia",
            name="direccion",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
