# Generated by Django 5.2.7 on 2025-11-11 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foro", "0004_incidencia_direccion"),
        ("usuario", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReaccionComentario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "comentario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reacciones",
                        to="foro.comentario",
                    ),
                ),
                (
                    "tipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="foro.tiporeaccion",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="usuario.perfil"
                    ),
                ),
            ],
            options={
                "verbose_name": "Reacción a comentario",
                "verbose_name_plural": "Reacciones a comentarios",
                "unique_together": {("usuario", "comentario", "tipo")},
            },
        ),
        migrations.CreateModel(
            name="ReaccionIncidencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "incidencia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reacciones",
                        to="foro.incidencia",
                    ),
                ),
                (
                    "tipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="foro.tiporeaccion",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="usuario.perfil"
                    ),
                ),
            ],
            options={
                "verbose_name": "Reacción a incidencia",
                "verbose_name_plural": "Reacciones a incidencias",
                "unique_together": {("usuario", "incidencia", "tipo")},
            },
        ),
        migrations.DeleteModel(
            name="Reaccion",
        ),
    ]
