# Generated by Django 5.2.7 on 2025-11-11 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('color_principal', models.CharField(default='#3B82F6', max_length=7)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Paradero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('es_popular', models.BooleanField(default=False)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Paradero',
                'verbose_name_plural': 'Paraderos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('sentido', models.CharField(choices=[('IDA', 'Ida'), ('VUELTA', 'Vuelta')], max_length=10)),
                ('color_linea', models.CharField(default='#EF4444', max_length=7)),
                ('grosor_linea', models.IntegerField(default=3)),
                ('coordenadas', models.JSONField()),
                ('archivo_kml', models.CharField(blank=True, max_length=255)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutas', to='rutas.empresa')),
            ],
            options={
                'verbose_name': 'Ruta',
                'verbose_name_plural': 'Rutas',
                'ordering': ['empresa', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='RutaParadero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField(default=0)),
                ('distancia_metros', models.FloatField()),
                ('paradero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paradero_rutas', to='rutas.paradero')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ruta_paraderos', to='rutas.ruta')),
            ],
            options={
                'verbose_name': 'Ruta-Paradero',
                'verbose_name_plural': 'Rutas-Paraderos',
                'ordering': ['ruta', 'orden'],
                'unique_together': {('ruta', 'paradero')},
            },
        ),
    ]
