# Generated by Django 5.2.7 on 2025-11-10 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruta',
            name='codigo',
            field=models.CharField(default='TEMP', max_length=20),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='nombre',
            field=models.CharField(default='Sin nombre', max_length=200),
        ),
    ]
