# Generated by Django 5.2.7 on 2025-11-11 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ruta',
            old_name='archivo_kml',
            new_name='archivo_kml_ida',
        ),
        migrations.RemoveField(
            model_name='ruta',
            name='coordenadas',
        ),
        migrations.RemoveField(
            model_name='ruta',
            name='sentido',
        ),
        migrations.AddField(
            model_name='ruta',
            name='archivo_kml_vuelta',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='ruta',
            name='coordenadas_ida',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ruta',
            name='coordenadas_vuelta',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
