# Generated by Django 5.2.7 on 2025-11-11 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0002_rename_archivo_kml_ruta_archivo_kml_ida_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ruta',
            options={'ordering': ['empresa', 'nombre'], 'verbose_name': 'Ruta', 'verbose_name_plural': 'Rutas'},
        ),
        migrations.RemoveField(
            model_name='ruta',
            name='archivo_kml_ida',
        ),
        migrations.RemoveField(
            model_name='ruta',
            name='archivo_kml_vuelta',
        ),
        migrations.RemoveField(
            model_name='ruta',
            name='color_linea',
        ),
        migrations.RemoveField(
            model_name='ruta',
            name='coordenadas_ida',
        ),
        migrations.RemoveField(
            model_name='ruta',
            name='coordenadas_vuelta',
        ),
        migrations.RemoveField(
            model_name='ruta',
            name='grosor_linea',
        ),
        migrations.AddField(
            model_name='ruta',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='Recorrido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentido', models.CharField(choices=[('IDA', 'Ida'), ('VUELTA', 'Vuelta')], max_length=10)),
                ('color_linea', models.CharField(default='#EF4444', max_length=7)),
                ('grosor_linea', models.IntegerField(default=3)),
                ('coordenadas', models.JSONField()),
                ('archivo_kml', models.CharField(blank=True, max_length=255)),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recorridos', to='rutas.ruta')),
            ],
            options={
                'verbose_name': 'Recorrido',
                'verbose_name_plural': 'Recorridos',
                'ordering': ['ruta', 'sentido'],
                'unique_together': {('ruta', 'sentido')},
            },
        ),
        migrations.CreateModel(
            name='RecorridoParadero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField(default=0)),
                ('distancia_metros', models.FloatField()),
                ('paradero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paradero_recorridos', to='rutas.paradero')),
                ('recorrido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recorrido_paraderos', to='rutas.recorrido')),
            ],
            options={
                'verbose_name': 'Recorrido-Paradero',
                'verbose_name_plural': 'Recorridos-Paraderos',
                'ordering': ['recorrido', 'orden'],
                'unique_together': {('recorrido', 'paradero')},
            },
        ),
        migrations.DeleteModel(
            name='RutaParadero',
        ),
    ]
